
# cargo-vet config file

[cargo-vet]
version = "0.9"

[imports.firefox]
url = "https://hg.mozilla.org/mozilla-central/raw-file/tip/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.aead]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.bech32]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.7.0"
criteria = "safe-to-deploy"

[[exemptions.chacha20]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.chacha20poly1305]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.cipher]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.cookie-factory]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "3.2.0"
criteria = "safe-to-deploy"

[[exemptions.dashmap]]
version = "4.0.2"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.find-crate]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.4"
criteria = "safe-to-deploy"

[[exemptions.hkdf]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.i18n-config]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.i18n-embed]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.i18n-embed-fl]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.i18n-embed-impl]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "6.2.1"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.11.2"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.pbkdf2]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.0.12"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.0.8"
criteria = "safe-to-deploy"

[[exemptions.poly1305]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.10"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.rand_hc]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.13"
criteria = "safe-to-deploy"

[[exemptions.rust-embed]]
version = "5.9.0"
criteria = "safe-to-deploy"

[[exemptions.rust-embed-impl]]
version = "5.9.0"
criteria = "safe-to-deploy"

[[exemptions.rust-embed-utils]]
version = "5.1.0"
criteria = "safe-to-deploy"

[[exemptions.salsa20]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.scrypt]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.self_cell]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.toml]]
version = "0.5.8"
criteria = "safe-to-deploy"

[[exemptions.type-map]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.9.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.36.1"
criteria = "safe-to-deploy"

[[exemptions.x25519-dalek]]
version = "1.1.1"
criteria = "safe-to-deploy"
