
# cargo-vet config file

[imports.firefox]
url = "https://hg.mozilla.org/mozilla-central/raw-file/tip/supply-chain/audits.toml"

[[exemptions.Inflector]]
version = "0.11.4"
criteria = "safe-to-deploy"

[[exemptions.aead]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.age-core]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.bech32]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bitvec]]
version = "0.19.5"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.7.0"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.4.3"
criteria = "safe-to-deploy"

[[exemptions.c2-chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.chacha20poly1305]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.cipher]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.cipher]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.cookie-factory]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.cpuid-bool]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.crypto-mac]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "3.2.0"
criteria = "safe-to-deploy"

[[exemptions.dashmap]]
version = "4.0.2"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.find-crate]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.fluent]]
version = "0.15.0"
criteria = "safe-to-deploy"

[[exemptions.fluent-bundle]]
version = "0.15.1"
criteria = "safe-to-deploy"

[[exemptions.funty]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.4"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-deploy"

[[exemptions.hkdf]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.hmac]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.i18n-config]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.i18n-embed]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.i18n-embed-fl]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.i18n-embed-impl]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.instant]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.53"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.101"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.14"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.3.4"
criteria = "safe-to-deploy"

[[exemptions.memory_units]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "6.2.1"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.opaque-debug]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.ouroboros]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.ouroboros_macro]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.11.2"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.pbkdf2]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.0.8"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.0.8"
criteria = "safe-to-deploy"

[[exemptions.poly1305]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.10"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error-attr]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.rand_hc]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.10"
criteria = "safe-to-deploy"

[[exemptions.rust-embed]]
version = "5.9.0"
criteria = "safe-to-deploy"

[[exemptions.rust-embed-impl]]
version = "5.9.0"
criteria = "safe-to-deploy"

[[exemptions.rust-embed-utils]]
version = "5.1.0"
criteria = "safe-to-deploy"

[[exemptions.salsa20]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.same-file]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.scrypt]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.130"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.130"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.6.1"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.75"
criteria = "safe-to-deploy"

[[exemptions.tap]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.28"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.28"
criteria = "safe-to-deploy"

[[exemptions.toml]]
version = "0.5.8"
criteria = "safe-to-deploy"

[[exemptions.type-map]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.universal-hash]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.3"
criteria = "safe-to-deploy"

[[exemptions.walkdir]]
version = "2.3.2"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.9.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.76"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.76"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.76"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.76"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.76"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.53"
criteria = "safe-to-deploy"

[[exemptions.wee_alloc]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.wyz]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.x25519-dalek]]
version = "1.1.1"
criteria = "safe-to-deploy"

